### PR TITLE
ESLint and Prettier setup instructions.

### PR DESCRIPTION
**Pull request by JimmyMcBride**
Creating some docs for setting up eslint and prettier in projects. This is the first draft, so let me know what you think and if anything needs to be changed. 

In .eslintrc.js, rules selection is blank. Are there any good rules you can think of that will help keep our codebase in line?

### CODE REVIEW

**Comment by berniedurfee** [comment]
This is awesome, thank! I'll bring this up at our next engineering meeting. We might want to split this between this document, for the standard, and the Labs guide, for the HowTo part.

**Comment by JimmyMcBride** [comment]
Cool deal! That mkdocs is really cool! :fire: I don't mind helping write it out at all if you need anything. I love to write technical documents, it's my jam. Feel free to add any suggestions or changes. :100:

**Comment by tinomen** [comment]
Holy cow. This is great. @berniedurfee would this be better suited for the [Labs Guides](https://github.com/Lambda-School-Labs/labs-guides/)?

**Comment by ryan-hamblin** [comment]
> Holy cow. This is great. @berniedurfee would this be better suited for the [Labs Guides](https://github.com/Lambda-School-Labs/labs-guides/)?

I think it should be in the guides for sure :)

**Comment by tinomen** [comment]
Closing since it's been submitted to the guides. Thank you @JimmyMcBride

**Pull request closed without merging**
